### PR TITLE
Add sentence to wait for login link

### PR DESCRIPTION
**Pull request by andrerom**
to unblock https://github.com/ezsystems/ezplatform/pull/34

review ping @ezsystems/qa-team

### CODE REVIEW

**Comment by joaoinacio** [comment]
(nitpick: `sentence`)

**Comment by andrerom** [comment]
thanks @joaoinacio, fixed.

**Comment by pcardiga** [comment]
seems ok
+1

**Comment by andrerom** [comment]
this will fail until platform pr have been merged.

**Pull request merged**
