### PR TITLE
Fix EZP-24476: Refactor CSRF token generation in Security login form

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24476

Ref https://github.com/ezsystems/ezpublish-kernel/pull/1318

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @pspanja @glye @yannickroger

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by glye** [comment]
+1

**Pull request merged**
