### PR TITLE
EZP-23949: add support for Platform Installer

### PR DESCRIPTION
**Pull request by bdunogier**
> Required changes for ezsystems/ezpublish-community#226
> Status: WIP

Contains legacy related changes:
- bdd tests
- missing zetacomponents/feed dependency
- legacy features in templates & controllers

## TODO
- [x] Add requirement of `ezsystems/demobundle-data:~0.1`
- [x] Think about splitting the elements and merging asap if possible (zetacomponents, legacy features based on a condition)
- [x] Figure out the viewbaseTemplate thing (78eda79)
- [x] See what can be done about the tests that require legacy. `@legacy` scenarii tags for the time being ?

### CODE REVIEW

**Comment by bdunogier** [comment]
Note: it looks like this should cover most, if not all, of the remaining legacy features.

**Comment by andrerom** [comment]
+1 if travis agrees

review ping @yannickroger @pspanja @lolautruche

**Comment by bdunogier** [comment]
Travis won't agree. It doesn't even agree with master right now :-)

**Comment by andrerom** [comment]
True :( which repos are affected by that?

**Comment by bdunogier** [comment]
ezpublish-community & DemoBundle. Maybe also BehatBundle.

**Comment by lolautruche** [comment]
+1

**Pull request merged**
