### PR TITLE
EZP-24717: Image alt attribute should not be shown when empty

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24717

### CODE REVIEW

**Comment by clash82** [comment]
@ezrobot you're so mysterious today...

**Comment by andrerom** [comment]
+1, as for ezrobot it is probably that cs needs to be fixed on this repo.

**Comment by clash82** [comment]
Thanks @andrerom 

ping @kamilmusial @SylvainGuittard

**Comment by crevillo** [comment]
+0.5. Alt attribute was required in html and there are some discussions and people arguing why html5 has made this optional... 
http://www.paciellogroup.com/blog/2008/02/alt-in-html5-required-to-be-or-not-to-be/
http://adrianroselli.com/2011/04/image-alt-attributes-not-always.html
Also, as said in http://stackoverflow.com/questions/7729918/is-value-for-alt-atrribute-not-required-in-html5-to-pass-validation, it not specified a screenreader will read the full path of the image instead of say nothing...

**Comment by kamilmusial** [comment]
+1

**Comment by clash82** [comment]
@crevillo thanks for details. DemoBundle is built on top of HTML5 so as you mention, `alt` attribute is optional.

**Comment by crevillo** [comment]
yes, but still... +0.5 :)

**Comment by clash82** [comment]
:beer: 0,5 - like them too ;)

**Comment by SylvainGuittard** [comment]
+1

**Comment by clash82** [comment]
ping @andrerom :)

**Pull request merged**
