### PR TITLE
Fix deprecated criteria clause

### PR DESCRIPTION
**Pull request by michalpipa**
Fix deprecated criteria clause.

JIRA issue: https://jira.ez.no/browse/EZP-24730

### CODE REVIEW

**Comment by clash82** [comment]
+1

**Comment by michalpipa** [comment]
ping @clash82 @andrerom @pspanja

**Comment by pspanja** [comment]
+1

**Comment by pspanja** [comment]
One job on Travis borked, I've just restarted so let's wait for it.

**Comment by SylvainGuittard** [comment]
+1

**Comment by pspanja** [comment]
All seems to be ok, it previously passed on the first and failed on the second, so it should just be a Travis problem. +1 it is.

**Comment by michalpipa** [comment]
Github has connectivity problems today: https://status.github.com/

That's why travis fails to clone repositories.

**Comment by andrerom** [comment]
+1

**Pull request merged**
