### PR TITLE
EZP-24087: Image stretched on the home page of the demo bundle

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24087

### CODE REVIEW

**Comment by yannickroger** [comment]
+1

**Comment by sunpietro** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
@clash82 Do you have merge access or should I merge it ?

**Comment by clash82** [comment]
@yannickroger I don't have merge access. If you would be so kind...

**Pull request merged**
