### PR TITLE
EZP-24940: Remove unused Repsonse object in DemoBundle FolderController

### PR DESCRIPTION
**Pull request by wizhippo**
The response is create but not used.  Also the content is retrieved but not used.

### CODE REVIEW

**Comment by andrerom** [comment]
Might rather be a bug? Or is the cache rules set somewhere else?

**Comment by wizhippo** [comment]
the cache is handled by the ez_content controller

**Comment by andrerom** [comment]
Ok clear, +1

ping @yannickroger @clash82 ?

**Comment by wizhippo** [comment]
https://jira.ez.no/browse/EZP-24940

**Comment by clash82** [comment]
Good work, thank you +1

**Pull request merged**
