### PR TITLE
EZP-24425 DemoBundle form fields appearing in red

### PR DESCRIPTION
**Pull request by crevillo**
Fixes https://jira.ez.no/browse/EZP-24425

looks like form[field].vars.errors is defined even is there no errors. We need to check if that is empty or not before adding the error class. 

ping @yannickroger @bdunogier @andrerom

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by crevillo** [comment]
ping @clash82 here too.

**Comment by clash82** [comment]
It looks as it should now, good work +1

**Comment by bdunogier** [comment]
+1

**Pull request merged**
