### PR TITLE
EZP-24938: Fix language switcher when no translation exists

### PR DESCRIPTION
**Pull request by wizhippo**
When a translation does not exist an exception is thrown.  This does not add the language if a valid url cannot be generated.

### CODE REVIEW

**Comment by yannickroger** [comment]
You should create a Jira issue. We need it to process any type of fixes (except for typos)

**Comment by wizhippo** [comment]
@yannickroger done thanks

**Comment by yannickroger** [comment]
ping @clash82

**Comment by clash82** [comment]
I would suggest to change commit name to include Jira ID, but besides this +1

**Comment by andrerom** [comment]
+1 ping @lolautruche

**Pull request closed without merging**
