### PR TITLE
[req] Updated components/bootstrap to ~3.3.2

### PR DESCRIPTION
**Pull request by bdunogier**
Fixes the dependency issue Travis was having with bootstrap (https://github.com/ezsystems/ezplatform/pull/15).

### CODE REVIEW

**Comment by bdunogier** [comment]
@andrerom / @clash82 any objection ?

**Comment by andrerom** [comment]
+1 ( @clash82 context: the hard coded version made composer fail, so we need to open the requirement a little bit here )

**Comment by clash82** [comment]
I would prefer to update it manually from time to time. We've discussed this with @bdunogier. I'll test if everything works and give a feedback.

closed... uh, where's the fire? ;-)

**Comment by bdunogier** [comment]
I'll update it manually then.

**Comment by andrerom** [comment]
> closed... uh, where's the fire? ;-)

sprint demo and release, and this popped up late blocking the whole thing.

Sub/patch release updates are a completely different beast then v2 to v3 (or even v3.2 to v3.3). As per [Semantic Versioning](http://semver.org/), which bootstrap apperently follows now, they are actively trying to avoid introducing any breaks in patch versions. So there might be some micro breaks, but this is demo bundle so we don't care.

**Pull request closed without merging**
