### PR TITLE
EZP-24150: Implement privacy cookie law in demo bundle

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24150

Work in progress.

Waiting for:
- [x] https://github.com/ezsystems/EzSystemsPrivacyCookieBundle/pull/1 merged and added to packagist
- [x] EzSystemsPrivacyCookieBundle dependency must be enabled in eZPublishKernel.php

### CODE REVIEW

**Comment by crevillo** [comment]
question... why we need a separate bundle for this?

**Comment by andrerom** [comment]
The idea was to make it reusable, also for real websites.

**Comment by crevillo** [comment]
then i'm ok. yes. makes totally sense.

**Comment by clash82** [comment]
All conditions are met, ready for merge.

**Comment by clash82** [comment]
Ahh, yes... tests...

**Comment by andrerom** [comment]
Please review on top of master so we can verify the updated travis setup works ()

**Comment by clash82** [comment]
ping @andrerom

**Comment by andrerom** [comment]
Thanks, but you did not rebase on top of master, so it might still break on merge. Sorry, but could you? :)
_It is still missing 4676aca54cd353ecf1b8eff0072c3a128cabd0f8 as parent basically_

**Comment by clash82** [comment]
Better now? ;)

**Comment by andrerom** [comment]
+1

**Pull request merged**
