### PR TITLE
EZP-24762: Remove unused "New Almighty" content object from demo_data.sql

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24762

### CODE REVIEW

**Comment by andrerom** [comment]
Missing change to ezmedia table, you can cherry pick my commit 782c7dc5b9fe9fc4e80d92e2105962d500cfe4aa.

There might also be data in other tables, I'll check the original PR.

**Comment by andrerom** [comment]
It's close to impossible to see the diff of the original PR given had no new lines. Can you try to have a look what was added somehow? to double check that we are not leaving any cruft in the database.

*Side: Be aware when we refer to cherry pick, we mean that the commit should be cherry picked and left as independent commit. While we rebase to get rid of own temporary commits and attempts, typically at the end of the process before merge, we don't get rid of history involving significance like if someone else has also contributed on parts of a combined work. Or if several topics is handled, then those are left as separate commits as well. For next time ;)*

**Comment by andrerom** [comment]
Ok, seems good, true to look for additional data related to this object and could not find any, +1

**Comment by clash82** [comment]
@andrerom thank you :) I didn't find anything more besides changes mentioned in this PR.

**Comment by andrerom** [comment]
Thanks, merged :)

**Pull request merged**
