### PR TITLE
EZP-24346: As a user of Platform and Studio UI, I want to have an almighty content type that includes all default field types of eZ Platform

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24346

See it [in action](https://www.youtube.com/watch?v=bSlfdjC0PAs).

### CODE REVIEW

**Comment by clash82** [comment]
ping @andrerom

**Comment by andrerom** [comment]
$a = @rolandbenedetti : What was the purpose of this task? Should it also contain field types we don't support yet like Tags, deprecated and otherwise missing fiedltypes?

if ( $a == 'it is fine like it is' )
    +1;

**Comment by clash82** [comment]
ping @rolandbenedetti

**Comment by rolandbenedetti73** [comment]
Sorry @andrerom @clash82 I usually see Github notification but this one went through the net.
It should contain only the field type listed in the requirement.
This is a content type that aim at making it simpler to show and explain all the default field types deliver with eZ Platform, it has no real use case purpose beside that one, hence it will only be in the demo bundle to serve that purpose.

**Pull request merged**
