### PR TITLE
Fix EZP-24482 - eZ Demo top menu doesn't appear until added a new folder after EZP-22361

### PR DESCRIPTION
**Pull request by pedroresende**
After updating DemoBundle to use the latest Bootstrap https://jira.ez.no/browse/EZP-22361 a regression has been introduced https://jira.ez.no/browse/EZP-20108

https://jira.ez.no/browse/EZP-24482

### CODE REVIEW

**Comment by yannickroger** [comment]
You should update the description with links to issues instead of just names.

**Comment by pedroresende** [comment]
@yannickroger updated, thanks :)

**Comment by yannickroger** [comment]
ping @clash82 ;) our bootstrap hero.

**Comment by clash82** [comment]
superman

Tested and approved +1

**Comment by SylvainGuittard** [comment]
The main issue is that we are using a customized bootstrap.css. We will face the same issue in the future if we will upgrade bootstrap.

Why not using the standard bootstrap.css and creating a new file (ezdemo.css) for our custom code?

**Comment by crevillo** [comment]
+100 to @SylvainGuittard suggestion.

**Comment by clash82** [comment]
> The main issue is that we are using a customized bootstrap.css. We will face the same issue in the future if we will upgrade bootstrap.

`bootstrap.css` is a compiled version of origin bootstrap less components and our customized version (take a look on `bootstrap.less` file to see how it works). This was part of my [super-hero bootstrap task](https://jira.ez.no/browse/EZP-22361).

I agree that it's not a perfect solution but it cover most of our current needs.

**Comment by pedroresende** [comment]
@clash82 @yannickroger ping....

**Comment by clash82** [comment]
+2

**Comment by yannickroger** [comment]
+1 final ping @SylvainGuittard

**Comment by SylvainGuittard** [comment]
+1

**Pull request merged**
