### PR TITLE
Fix EZP-24052: Preview causes redirect to versionview not being able to continue editing

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24052

See https://github.com/ezsystems/LegacyBridge/pull/23

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @dpobel @glye @pspanja @yannickroger

**Comment by andrerom** [comment]
won't this break when not having legacy bridge installed?

**Comment by lolautruche** [comment]
You're right, fixed :blush:

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1

**Pull request merged**
